#!/bin/bash

echo -n "$GC_SA" | base64 -d > credentials.json

cat << EOF > .env
DISCORD_TOKEN=$DISCORD_TOKEN
ADMIN_ROLE_ID=$ADMIN_ROLE_ID
PREFIX=$PREFIX
CHANNELS=$CHANNELS
PLAYLIST_ID=$PLAYLIST_ID
CLIENT_ID=$CLIENT_ID
CLIENT_SECRET=$CLIENT_SECRET
EOF